{
    'name': 'Helpdesk Management',
    'summary': """
        Helpdesk""",
    'version': '12.0.1.22.1',
    'license': 'AGPL-3',
    'category': 'After-Sales',
    'author': 'Ariel Cerrato ',
    'website': 'https://guip.com',
    'depends': [
        'mail',
        'portal',
    ],
    'data': [
        'data/helpdesk_data.xml',
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'views/res_partner_view.xml',
        'views/helpdesk_ticket_templates.xml',
        'views/helpdesk_ticket_menu.xml',
        'views/helpdesk_ticket_team_view.xml',
        'views/helpdesk_ticket_stage_view.xml',
        'views/helpdesk_ticket_category_view.xml',
        'views/helpdesk_ticket_sub_category_view.xml',
        'views/helpdesk_ticket_channel_view.xml',
        'views/helpdesk_ticket_tag_view.xml',
        'views/helpdesk_ticket_view.xml',
        'views/helpdesk_dashboard_view.xml',
        'views/report_helpdesk_ticket.xml',
        'views/helpdesk_ticket_sitio_view.xml',
        'data/ir.cron.xml',
    ],
    'demo': [
        'demo/helpdesk_demo.xml',
    ],
    'development_status': 'Beta',
    'application': True,
    'installable': True,
}
